[build]
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "SUPABASE_URL"

[dev]
  port = 8888

# Redirect all paths to index.html for client-side routing
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

[functions]
  directory    = "netlify/functions"
  node_bundler = "esbuild"
